[package]
name = "ruscal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
nom_locate = "4.1.0"
pest = "2.5.6"
pest_derive = "2.5.6"
